spring:
  application:
    name: health-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5439/health_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:health-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:d17hPRAz1H8kWs7XIyBOieoDl4qzkaus}
  web:
    cors:
      allowed-origins:
        - http://localhost:3000
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: ${SERVER_PORT:8089}
