spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5434/user_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6381}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        spring.json:
          value.default.type: java.util.Map
          trusted.packages: '*'
          use.type.headers: false
        spring.deserializer:
          key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:user-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:KIWfKreN9sVqxFibdShwYodDdtgjiqHq}
business:
  kafka:
    topics:
      user-update:
        name: user.update.v1
        partitions: 1
        replicas: 1
      user-role-update:
        name: user.role-update.v1
        partitions: 1
        replicas: 1
      user-status-update:
        name: user.status-update.v1
        partitions: 1
        replicas: 1
      user-preferences-creation:
        name: user.preferences-creation.v1
        partitions: 1
        replicas: 1
      user-contacts-creation:
        name: user-contacts.creation.v1
        partitions: 1
        replicas: 1
      cart-creation:
        name: cart.creation.v1
        partitions: 1
        replicas: 1
      user-creation:
        name: user.creation.v1
        consumer:
          group-id: user.creation.consumer.group
  cache:
    user-profile:
      name: ${CACHE_USER_PROFILE_NAME:userProfileCache}
      ttl: ${CACHE_USER_PROFILE_TTL:7200}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
server:
  port: ${SERVER_PORT:8082}
