spring:
  application:
    name: preference-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5438/preference_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6383}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
business:
  cache:
    user-preference:
      name: ${CACHE_USER_PREFERENCE_NAME:userPreferenceCache}
      ttl: ${CACHE_USER_PREFERENCE_TTL:3600}
server:
  port: ${SERVER_PORT:8088}
