spring:
  application:
    name: preference-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5438/preference_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
mongock:
  migration-scan-package: com.cabaggregator.recommendationservice.migration
  transactional: true
  enabled: true
server:
  port: ${SERVER_PORT:8088}
