spring:
  application:
    name: preference-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5438/preference_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6383}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        spring.json:
          value.default.type: java.util.Map
          trusted.packages: '*'
          use.type.headers: false
        spring.deserializer:
          key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
business:
  kafka:
    topics:
      user-preferences-creation:
        name: user.preferences-creation.v1
        consumer:
          group-id: user.preferences-creation.consumer.group
  cache:
    user-preferences:
      name: ${CACHE_USER_PREFERENCES_NAME:userPreferencesCache}
      ttl: ${CACHE_USER_PREFERENCES_TTL:3600}
server:
  port: ${SERVER_PORT:8088}
