spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/cab-aggregator-realm/protocol/openid-connect/certs}
business:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:mealmap-realm}
    grant-type: ${KEYCLOAK_GRANT_TYPE:client_credentials}
    email-service:
      enabled: ${KEYCLOAK_EMAIL_SERVICE_ENABLED:false}
    admin:
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:5OpVHHUSEP3O8tSk3MbjTxx6Efn5ASUl}
    client:
      client-id: ${KEYCLOAK_CLIENT_CLIENT_SECRET:mealmap-client}
      client-secret: ${KEYCLOAK_CLIENT_CLIENT_SECRET:CikyzVJQFlmJaa3TsM7SJi8Y76edNtgS}
server:
  port: ${SERVER_PORT:8083}
