spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost:27026}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
      replica-set-name: ${DB_REPLICA_SET_NAME:rs0}
      database: ${DB_NAME:notification_service}
mongock:
  migration-scan-package: com.mealmap.notificationservice.migration
  transactional: true
  enabled: true
server:
  port: ${SERVER_PORT:8091}
