export enum OrderSortField {
  ID = "ID",
  USER_ID = "USER_ID",
  DELIVERY_ADDRESS = "DELIVERY_ADDRESS",
  ORDER_STATUS = "ORDER_STATUS",
  TOTAL_AMOUNT = "TOTAL_AMOUNT",
  DISCOUNT_AMOUNT = "DISCOUNT_AMOUNT",
  PAYMENT_STATUS = "PAYMENT_STATUS",
  ORDERED_AT = "ORDERED_AT",
  READY_AT = "READY_AT",
  COMPLETED_AT = "COMPLETED_AT",
}
