version: "3.7"

services:

  product-pg-database:
    image: postgres:17
    container_name: mealmap-product-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: product_database
    ports:
      - "5433:5432"
    volumes:
      - product-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  user-pg-database:
    image: postgres:17
    container_name: mealmap-user-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: user_database
    ports:
      - "5434:5432"
    volumes:
      - user-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  organization-pg-database:
    image: postgres:17
    container_name: mealmap-organization-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: organization_database
    ports:
      - "5437:5432"
    volumes:
      - organization-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  cart-pg-database:
    image: postgres:17
    container_name: mealmap-cart-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cart_database
    ports:
      - "5436:5432"
    volumes:
      - cart-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  preference-pg-database:
    image: postgres:17
    container_name: mealmap-preference-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: preference_database
    ports:
      - "5438:5432"
    volumes:
      - preference-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  health-pg-database:
    image: postgres:17
    container_name: mealmap-health-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: health_database
    ports:
      - "5439:5432"
    volumes:
      - health-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  keycloak-pg-database:
    image: postgres:17
    container_name: mealmap-keycloak-pg-database
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak_db
    ports:
      - "5435:5432"
    volumes:
      - keycloak-pg-database_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  order-mongo-database1:
    container_name: mealmap-order-mongo-database1
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27020:27017"
    volumes:
      - order-mongo-database1_data:/data/db
    healthcheck:
      test: test $$(mongosh --port 27017 --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"order-mongo-database1:27017\",priority:1}, {_id:1,host:\"order-mongo-database2:27017\",priority:0}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - mealmap-network
    depends_on:
      - order-mongo-database2

  order-mongo-database2:
    container_name: mealmap-order-mongo-database2
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27021:27017"
    volumes:
      - order-mongo-database2_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - mealmap-network

  promo-mongo-database1:
    container_name: mealmap-promo-mongo-database1
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27022:27017"
    volumes:
      - promo-mongo-database1_data:/data/db
    healthcheck:
      test: test $$(mongosh --port 27017 --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"promo-mongo-database1:27017\",priority:1}, {_id:1,host:\"promo-mongo-database2:27017\",priority:0}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - mealmap-network
    depends_on:
      - promo-mongo-database2

  promo-mongo-database2:
    container_name: mealmap-promo-mongo-database2
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27023:27017"
    volumes:
      - promo-mongo-database2_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - mealmap-network

  recommendation-mongo-database1:
    container_name: mealmap-recommendation-mongo-database1
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27024:27017"
    volumes:
      - recommendation-mongo-database1_data:/data/db
    healthcheck:
      test: test $$(mongosh --port 27017 --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"recommendation-mongo-database1:27017\",priority:1}, {_id:1,host:\"recommendation-mongo-database2:27017\",priority:0}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - mealmap-network
    depends_on:
      - recommendation-mongo-database2

  recommendation-mongo-database2:
    container_name: mealmap-recommendation-mongo-database2
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27025:27017"
    volumes:
      - recommendation-mongo-database2_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - mealmap-network

  notification-mongo-database1:
    container_name: mealmap-notification-mongo-database1
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27026:27017"
    volumes:
      - notification-mongo-database1_data:/data/db
    healthcheck:
      test: test $$(mongosh --port 27017 --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"notification-mongo-database1:27017\",priority:1}, {_id:1,host:\"notification-mongo-database2:27017\",priority:0}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
    networks:
      - mealmap-network
    depends_on:
      - notification-mongo-database2

  notification-mongo-database2:
    container_name: mealmap-notification-mongo-database2
    image: mongo:7.0
    command: [ "--replSet", "rs0", "--bind_ip", "0.0.0.0", "--port", "27017" ]
    ports:
      - "27027:27017"
    volumes:
      - notification-mongo-database2_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    networks:
      - mealmap-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: mealmap-pgadmin
    restart: on-failure
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - ./management/pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - mealmap-network

  product-redis:
    image: redis:7.4-alpine
    container_name: mealmap-product-redis-server
    restart: on-failure
    ports:
      - "6380:6379"
    environment:
      REDIS_PASSWORD: password
    volumes:
      - product-redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  user-redis:
    image: redis:7.4-alpine
    container_name: mealmap-user-redis-server
    restart: on-failure
    ports:
      - "6381:6379"
    environment:
      REDIS_PASSWORD: password
    volumes:
      - user-redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  organization-redis:
    image: redis:7.4-alpine
    container_name: mealmap-organization-redis-server
    restart: on-failure
    ports:
      - "6382:6379"
    environment:
      REDIS_PASSWORD: password
    volumes:
      - organization-redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  preference-redis:
    image: redis:7.4-alpine
    container_name: mealmap-preference-redis-server
    restart: on-failure
    ports:
      - "6383:6379"
    environment:
      REDIS_PASSWORD: password
    volumes:
      - preference-redis_data:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      start_period: 20s
      retries: 5
    networks:
      - mealmap-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
    container_name: mealmap-keycloak
    restart: on-failure
    command: start-dev --import-realm --health-enabled=true --metrics-enabled=true --features=scripts
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./system-services/keycloak/export:/opt/keycloak/data/import
    environment:
      KC_HTTP_PORT: 8080
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-pg-database
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_FEATURES: token-exchange,admin-fine-grained-authz
    networks:
      - mealmap-network
    depends_on:
      - keycloak-pg-database

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: mealmap-minio
    ports:
      - "9002:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  zookeeper:
    image: zookeeper:3.7.0
    container_name: mealmap-zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    healthcheck:
      test: nc -z 127.0.0.1 2181 || exit -1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - mealmap-network

  kafka:
    image: obsidiandynamics/kafka
    container_name: mealmap-kafka
    restart: on-failure
    ports:
      - "9092:9092"
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    healthcheck:
      test: kafka-topics --bootstrap-server localhost:29092 --list
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    networks:
      - mealmap-network
    depends_on:
      - zookeeper

  elasticsearch:
    build:
      context: ./system-services/elasticsearch
      dockerfile: Dockerfile
    container_name: mealmap-product-elasticsearch
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:Z
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
    healthcheck:
      test: curl --silent --fail http://localhost:9200/_cluster/health || exit 1
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 5
    networks:
      - mealmap-network

volumes:
  product-pg-database_data:
  user-pg-database_data:
  organization-pg-database_data:
  cart-pg-database_data:
  preference-pg-database_data:
  health-pg-database_data:
  keycloak-pg-database_data:
  order-mongo-database1_data:
  order-mongo-database2_data:
  promo-mongo-database1_data:
  promo-mongo-database2_data:
  recommendation-mongo-database1_data:
  recommendation-mongo-database2_data:
  notification-mongo-database1_data:
  notification-mongo-database2_data:
  product-redis_data:
  user-redis_data:
  organization-redis_data:
  preference-redis_data:
  elasticsearch_data:
  minio_data:

networks:
  mealmap-network:
    driver: bridge
