spring:
  application:
    name: organization-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5437/organization_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6382}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
cache:
  organization:
    name: ${CACHE_ORGANIZATION_NAME:organizationCache}
    ttl: ${CACHE_ORGANIZATION_TTL:7200}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:organization-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:OEFH4kqAgr7DdKYim6ZVo5O30kaWXagN}
  web:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGINS_LOCALHOST:http://localhost:3000}
        - ${ALLOWED_ORIGINS_PRODUCTION:http://172.20.10.4:3000}
    open-endpoints:
      actuator:
        - /actuator/**
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  logstash:
    server: ${LOGSTASH_HOSTPORT:localhost:5000}
server:
  port: ${SERVER_PORT:8087}
