spring:
  application:
    name: auth-service
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      properties:
        spring.json:
          value.default.type: java.util.Map
          trusted.packages: '*'
          use.type.headers: false
        spring.deserializer:
          key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
          value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8080/realms/mealmap-realm/protocol/openid-connect/certs}
business:
  keycloak:
    server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080}
    realm: ${KEYCLOAK_REALM:mealmap-realm}
    grant-type: ${KEYCLOAK_GRANT_TYPE:client_credentials}
    email-service:
      enabled: ${KEYCLOAK_EMAIL_SERVICE_ENABLED:false}
    client:
      client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:auth-service}
      client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:gbLelnwDQ3xKPvokRNSRX1rriyhhU2rd}
  kafka:
    topics:
      user-creation:
        name: user.creation.v1
        partitions: 1
        replicas: 1
      user-update:
        name: user.update.v1
        consumer:
          group-id: user.update.consumer.group
      user-role-update:
        name: user.role-update.v1
        consumer:
          group-id: user.role-update.consumer.group
      user-status-update:
        name: user.status-update.v1
        consumer:
          group-id: user.status-update.group
  services:
    organization:
      name: ${ORGANIZATION_API_NAME:organization-service}
      path: ${ORGANIZATION_API_PATH:api/v1/organizations}
keycloak:
  token-refresh-interval: ${KEYCLOAK_TOKEN_REFRESH_INTERVAL:300}
security:
  web:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGINS_LOCALHOST:http://localhost:3000}
        - ${ALLOWED_ORIGINS_PRODUCTION:http://172.20.10.4:3000}
    open-endpoints:
      actuator:
        - /actuator/**
      open-api:
        - /swagger-ui/**
        - /swagger-resources/**
        - /v3/api-docs/**
        - /v3/api-docs.yaml
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
logging:
  logstash:
    server: ${LOGSTASH_HOSTPORT:localhost:5000}
server:
  port: ${SERVER_PORT:8083}
