spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5433/product_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  elasticsearch:
    uris: http://${ELASTICSEARCH_URL:localhost:9200}
    username: ${ELASTICSEARCH_USERNAME:elastic}
    password: ${ELASTICSEARCH_PASSWORD:elastic}
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
cache:
  product:
    name: ${CACHE_PRODUCT_NAME:productCache}
    ttl: ${CACHE_PRODUCT_TTL:3600}
  category:
    name: ${CACHE_CATEGORY_NAME:categoryCache}
    ttl: ${CACHE_CATEGORY_TTL:36000}
  allergen:
    name: ${CACHE_CATEGORY_NAME:allergenCache}
    ttl: ${CACHE_CATEGORY_TTL:86400}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:product-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:HtJsADcOSQfg8PYWlrgK7umZZxDeBZ7V}
  web:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGINS_LOCALHOST:http://localhost:3000}
        - ${ALLOWED_ORIGINS_PRODUCTION:http://172.20.10.4:3000}
    open-endpoints:
      actuator:
        - /actuator/**
business:
  newness:
    period: ${NEWNESS_PERIOD:10}
  elasticsearch:
    product:
      sync:
        enabled: ${ELASTIC_PRODUCT_SYNC_ENABLED:true}
        interval: ${ELASTIC_PRODUCT_SYNC_INTERVAL:3600}
    category:
      sync:
        enabled: ${ELASTIC_CATEGORY_SYNC_ENABLED:true}
        interval: ${ELASTIC_CATEGORY_SYNC_INTERVAL:36000}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
logging:
  logstash:
    server: ${LOGSTASH_HOSTPORT:localhost:5000}
server:
  port: ${SERVER_PORT:8081}
