spring:
  application:
    name: health-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5439/health_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: ${SERVER_PORT:8089}
