spring:
  application:
    name: file-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6384}
      password: ${REDIS_PASSWORD:password}
      database: ${REDIS_DATABASE:0}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
minio:
  url: ${MINIO_URL:http://localhost:9002}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  buckets:
    - ${MINIO_BUCKETS_PRODUCTS:products}
    - ${MINIO_BUCKETS_CATEGORIES:categories}
    - ${MINIO_BUCKETS_PRODUCTS:organizations}
cache:
  file:
    name: ${CACHE_FILE_NAME:fileCache}
    ttl: ${CACHE_FILE_TTL:300}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:file-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:rlceoDknbCkoqCz72jEhzjbfhhDid8uz}
  web:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGINS_LOCALHOST:http://localhost:3000}
        - ${ALLOWED_ORIGINS_PRODUCTION:http://172.20.10.4:3000}
    open-endpoints:
      actuator:
        - /actuator/**
      open-api:
        - /swagger-ui/**
        - /swagger-resources/**
        - /v3/api-docs/**
        - /v3/api-docs.yaml
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
logging:
  logstash:
    server: ${LOGSTASH_HOSTPORT:localhost:5000}
server:
  port: ${SERVER_PORT:8093}
