spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5434/user_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
server:
  port: ${SERVER_PORT:8082}
