spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost:27020}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
      replica-set-name: ${DB_REPLICA_SET_NAME:rs0}
      database: ${DB_NAME:order_database}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:order-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:iTQe3mUJH8Fe6cjvc7gT2DVWxjTDQjq7}
  web:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGINS_LOCALHOST:http://localhost:3000}
        - ${ALLOWED_ORIGINS_PRODUCTION:http://172.20.10.4:3000}
    open-endpoints:
      actuator:
        - /actuator/**
      open-api:
        - /swagger-ui/**
        - /swagger-resources/**
        - /v3/api-docs/**
        - /v3/api-docs.yaml
mongock:
  migration-scan-package: com.mealmap.orderservice.migration
  transactional: true
  enabled: true
business:
  services:
    promo-code:
      name: ${PROMO_API_NAME:promo-service}
      path: ${PROMO_API_PATH:api/v1/promo-codes}
    promo-stat:
      name: ${PROMO_API_NAME:promo-service}
      path: ${PROMO_API_PATH:api/v1/promo-stats}
    product:
      name: ${PRODUCT_API_NAME:product-service}
      path: ${PRODUCT_API_PATH:api/v1/products}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info,metrics
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_TRACING_ENDPOINT:http://localhost:9411/api/v2/spans}
logging:
  logstash:
    server: ${LOGSTASH_HOSTPORT:localhost:5000}
server:
  port: ${SERVER_PORT:8084}
