spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost:27020}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
      replica-set-name: ${DB_REPLICA_SET_NAME:rs0}
      database: ${DB_NAME:order_database}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
mongock:
  migration-scan-package: com.mealmap.orderservice.migration
  transactional: true
  enabled: true
business:
  services:
    promo-code:
      url: ${PROMO_CODE_API_URL:http://localhost:8086/api/v1/promo-codes/}
    promo-stat:
      url: ${PROMO_STAT_API_URL:http://localhost:8086/api/v1/promo-stats/}
    product:
      url: ${PRODUCT_API_URL:http://localhost:8081/api/v1/products/}
server:
  port: ${SERVER_PORT:8084}
