spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost:27020}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
      replica-set-name: ${DB_REPLICA_SET_NAME:rs0}
      database: ${DB_NAME:order_database}
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:order-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:iTQe3mUJH8Fe6cjvc7gT2DVWxjTDQjq7}
  web:
    cors:
      allowed-origins:
        - ${ALLOWED_ORIGINS_LOCALHOST:http://localhost:3000}
        - ${ALLOWED_ORIGINS_PRODUCTION:http://172.20.10.4:3000}
mongock:
  migration-scan-package: com.mealmap.orderservice.migration
  transactional: true
  enabled: true
business:
  services:
    promo-code:
      name: ${PROMO_API_NAME:promo-service}
      path: ${PROMO_API_PATH:api/v1/promo-codes}
    promo-stat:
      name: ${PROMO_API_NAME:promo-service}
      path: ${PROMO_API_PATH:api/v1/promo-stats}
    product:
      name: ${PRODUCT_API_NAME:product-service}
      path: ${PRODUCT_API_PATH:api/v1/products}
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: ${SERVER_PORT:8084}
