spring:
  application:
    name: telegram-bot
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
telegram:
  bot:
    token: ${TG_BOT_TOKEN:7509632284:AAGcvu3Jnq4Ey7CufazKKLxQmr54Xlig_eg}
    username: ${TG_BOT_USERNAME:CustomPublisherBot}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:telegram-bot}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:fGxyiddJQOB4mHOQhPDXJJk27ItCYwfI}
  web:
    cors:
      allowed-origins:
        - http://localhost:3000
business:
  kafka:
    topics:
      user-contacts-update-tg-chat:
        name: user-contacts.update-tg-chat.v1
        partitions: 1
        replicas: 1
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: ${SERVER_PORT:8092}
