global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9090

  - job_name: 'discover-with-eureka'
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /actuator/prometheus
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka
        refresh_interval: 30s
    relabel_configs:
    - source_labels: [__meta_eureka_app_name]
      target_label: application
    - source_labels: [__address__]
      target_label: instance
