spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5436/cart_database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
business:
  cart:
    max-item-quantity-in-cart: ${CART_MAX_ITEM_QUANTITY_IN_CART:20}
    max-product-quantity-in-cart: ${CART_MAX_PRODUCT_QUANTITY_IN_ITEM:20}
server:
  port: ${SERVER_PORT:8085}
