spring:
  application:
    name: promo-service
  data:
    mongodb:
      uri: mongodb://${DB_URL:localhost:27022}
      username: ${DB_USERNAME:mongo}
      password: ${DB_PASSWORD:root}
      replica-set-name: ${DB_REPLICA_SET_NAME:rs0}
      database: ${DB_NAME:promo_database}
security:
  oauth2:
    client:
      client-id: ${OAUTH2_CLIENT_CLIENT_ID:promo-service}
      client-secret: ${OAUTH2_CLIENT_CLIENT_SECRET:JHcA6IvV87TLa9HisfZU232rkkjmLPGm}
  web:
    cors:
      allowed-origins:
        - http://localhost:3000
mongock:
  migration-scan-package: com.mealmap.promoservice.migration
  transactional: true
  enabled: true
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
server:
  port: ${SERVER_PORT:8086}
